cookie:
  expiry_days: 30
  key: omsakthi
  name: streamlit_auth
credentials:
  usernames:
    admin:
      email: maruvoorhelp@gmail.com
      failed_login_attempts: 0
      logged_in: True
      name: Administrator
      password: mnp@1910
