cookie:
  expiry_days: 30
  key: omsakthi
  name: passkey
credentials:
  usernames:
    admin:
      email: maruvoorhelp@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Administrator
      password: mnp2025
